# Generated by Django 3.1.2 on 2020-10-16 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('megamix', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_ulr', models.ImageField(upload_to='programmers/')),
                ('name', models.CharField(max_length=32)),
                ('discription', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='programming_language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_name', models.CharField(max_length=32, unique=True)),
                ('icon', models.ImageField(height_field=64, null=True, upload_to='languages_icon/', width_field=64)),
                ('description', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('describe', models.CharField(max_length=1024)),
                ('image', models.ImageField(upload_to='projects/')),
                ('language', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='megamix.programming_language', verbose_name='language_name')),
                ('programmer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='megamix.member')),
            ],
        ),
        migrations.DeleteModel(
            name='members',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='language',
        ),
        migrations.DeleteModel(
            name='programming_languages',
        ),
        migrations.DeleteModel(
            name='projects',
        ),
    ]
