# Generated by Django 3.1.2 on 2020-10-16 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('megamix', '0002_auto_20201016_1244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programming_language',
            name='description',
        ),
        migrations.AlterField(
            model_name='programming_language',
            name='icon',
            field=models.ImageField(null=True, upload_to='languages_icon/'),
        ),
    ]
