# Generated by Django 3.1.2 on 2020-10-16 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('megamix', '0003_auto_20201016_1301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='programmer',
        ),
        migrations.AddField(
            model_name='project',
            name='programmer',
            field=models.ManyToManyField(to='megamix.member'),
        ),
    ]
