# Generated by Django 3.1.2 on 2020-10-16 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('megamix', '0004_auto_20201016_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='programmer',
        ),
    ]
