# Generated by Django 3.1.2 on 2020-10-16 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('megamix', '0005_remove_project_programmer'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='programmers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='megamix.member'),
        ),
    ]
