# Generated by Django 3.1.2 on 2020-10-16 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('megamix', '0006_project_programmers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='image_ulr',
            field=models.ImageField(default=None, upload_to='programmers/'),
        ),
        migrations.AlterField(
            model_name='programming_language',
            name='icon',
            field=models.ImageField(default=None, null=True, upload_to='languages_icon/'),
        ),
        migrations.AlterField(
            model_name='programming_language',
            name='language_name',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(default=None, upload_to='projects/'),
        ),
    ]
