# Generated by Django 3.1.2 on 2020-10-16 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('megamix', '0007_auto_20201016_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='megamix.programming_language'),
        ),
    ]
